### ISSUE TITLE
feature: open new window with middle-click on taskbar entry (workaround: manually add to start menu)

### ISSUE THREAD

**Issue by AlisterH** [alexd/metapad#5]
I realise you're not looking for feature requests, but anyway :)
Recent versions of windows support middle-clicking on a program in the taskbar to create a new file/window.  This works with notepad, but it doesn't work with metapad, and it would be much better if it did.

**Comment by sobitcorp** [comment]
This is not a metapad issue, rather a side effect from metapad not using an installer and therefore not adding a start-menu entry for itself.

See: https://stackoverflow.com/questions/6804873/new-instance-on-taskbar-middle-click-shiftclick

tl;dr: Create shortcut in your start menu to metapad executable or just pin it to taskbar.

This could be further 'fixed' by adding the ability to have metapad insert itself to the start menu but do we want such a feature in a program that's meant to be super-portable?

**Comment by AlisterH** [comment]
Thanks for the reply.  It turns out I added it to my start menu and have been happily middle-clicking on it for a long time, having forgotten about this ticket.

**Comment by skst** [comment]
FWIW, I do not pin metapad to my Start menu, but I do pin it to my taskbar, and the middle-click (or shift-click) still starts a new instance.

**Comment by Gitoffthelawn** [comment]
Hello! Nice to see I'm not the only one still using this well-written and highly functional application.

After all these years using Windows (and metapad), I completely forgot you could middle-click on a shortcut to open a new window.  Of course maybe that's because I didn't even have a middle button until a few years ago! ;)

I find it funny that this functionality seems to work as expected on metapad, but not on Notepad++.  Another example of "old" tech still working great!

Alex, if you're still around, thank you for this great tool.  I remember you working on it well before you were a parent... I'm wondering if your kid(s) are at a university by now!

**Comment by sobitcorp** [comment]
For anyone still using metapad, I just released a major update.
Check it out if you'd like :)
https://github.com/sobitcorp/metapad

**Comment by Gitoffthelawn** [comment]
> For anyone still using metapad, I just released a major update. Check it out if you'd like :) https://github.com/sobitcorp/metapad

Wow, after all these years, that's exciting news.

Who is "I"?  Is that Alex, or someone else?
